version: "3.8"
services:
  timescaledb:
    image: timescale/timescaledb:2.15.2-pg15
    container_name: timescaledb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - "./data/postgresql:/var/lib/postgresql/data"
      - ./init:/docker-entrypoint-initdb.d
      